name: autism_empowering
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animate_do: ^4.2.0
  animated_text_kit: ^4.2.1
  awesome_notifications: ^0.10.0
  bloc: ^9.0.0
  blurry_modal_progress_hud: ^1.1.1
  build_runner: ^2.4.13
  cloud_firestore: ^5.6.0
  collection: ^1.15.0
  crop: ^0.5.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^10.1.9
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^19.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.4
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.1
  flutter_sound: ^9.17.8
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^3.0.0
  get: ^4.6.6
  get_it: ^8.0.3
  go_router: ^15.1.2
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  isolated_worker: ^0.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  lottie: ^3.2.0
  motion_toast: ^2.9.1
  onesignal_flutter: ^5.2.0
  palette_generator: ^0.3.3
  path_provider: ^2.1.3
  permission_handler: ^12.0.0+1
  rive: ^0.13.20
  shared_preferences: ^2.2.3
  tflite:
    git:
      url: https://github.com/tech-ramakant/flutter_tflite.git
      ref: Namespace_not_specified_fix
  timezone: ^0.10.0
  tuple: ^2.0.2
  uuid: ^4.5.1
  voice_message_package: ^2.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/models/face_model.tflite
    - assets/models/labels.txt
    - assets/animals/
    - assets/fruits/
    - assets/animations/
    - assets/rive/dash.riv
  fonts:
    - family: tajwal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans-Bold.ttf
